### ISSUE TITLE
How to get values in stable-status as opposed to volatile-status?

### ISSUE THREAD

**Issue by promiseofcake** [davido/bazel_printy#1]
I noticed your project somehow has the build information as part of `stable-status.txt`, while the `get_workspace_status` file in Bazel [tools/buildstamp/get_workspace_status@1314570](https://github.com/bazelbuild/bazel/blob/1314570/tools/buildstamp/get_workspace_status) always writes to `volatile-status.txt`. How did you manage that?

**Comment by promiseofcake** [comment]
Oh I see, it's somehow linked to the prefix of the output command as `STABLE_`, does that have any negative effect on your build dependency graph?

**Comment by davido** [comment]
Yes, see:

https://github.com/bazelbuild/bazel/blob/3d1a194ff9e76f25f1a7242ff2d021523ba8e4a0/src/main/java/com/google/devtools/build/lib/bazel/BazelWorkspaceStatusModule.java#L150-L152

Nope. We use it the same way in Gerrit Code Review, and it works as expected:

https://github.com/GerritCodeReview/gerrit/blob/master/tools/workspace-status.sh#L17-L22
